config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'employees#index', as: 'home'

  #get 'employees#new', as: 'new'
    
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
	validates :name, presence: true,
						 length: {minimum: 2}
	validates :age, :designation,:gender, presence: true
	validates_numericality_of :age, :message=>'should be in number.'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	
	def index
		@employee = Employee.all
	end

	def new
		@employee = Employee.new 
	end
	
	def show
		@employee = Employee.find(params[:id])
	end
	
	def create
		@employee = Employee.new(employee_params)
		
		if(@employee.save)
			redirect_to @employee
		else
			render 'new'
		end
	end
	
	def edit
			@employee = Employee.find(params[:id])
	end
	
	def update
		@employee = Employee.find(params[:id])
		
		if(@employee.update(employee_params))
			redirect_to @employee
		else
			render 'edit'
		end
	end
	
	def destroy
		@employee = Employee.find(params[:id])
		@employee.destroy
		redirect_to @employee
	end
	
	private def employee_params
		params.require(:employee).permit(:name, :age, :designation, :gender)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<h2 style="color:orange;">Edit Employee</h2>

<hr>
<%= form_for @employee, method: :patch do |f| %>

	 <% if @employee.errors.any? %>
		<% @employee.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>

	<p>
		<h5><b><%= f.label :name %><br></b></h5>
		<%= f.text_field :name %>	
	</p>

	<p>
		<h5><b><%= f.label :age %><br></b></h5>
		<%= f.text_field :age %>	
	</p>
	
	<p>
		<h5><b><%= f.label :designation %><br></b></h5>
		<%= f.text_field :designation %>	
	</p>
	
	<p>
		<h5><b> <%= f.label :gender %><br></b></h5>	
 		<%= f.radio_button(:gender, 'male') %>
 		<b><%= f.label("Male", :Male) %></b>
		<%= f.radio_button(:gender, 'female')%>
		<b><%= f.label("Female", :Female) %></b>
	</p>
<hr>
	<p>
	<%= f.submit({:class => 'btn  btn-warning'}) %>
	</p>

<% end %>

app/views/employees/index.html.erb
<hr>
<h2 style="color:#a04000;">All Employees List</h2>
<hr><br>
 
  <% @employee.each do |e| %>
    <div class="well">
	 	<h2><%= e.name %></h2>
	 	<%= link_to  "View More >>", e, :class => 'btn btn-success btn-sm' %>
    </div>
<hr>

  <% end %>

app/views/employees/new.html.erb
<h2 style="color:blue;">New Employee</h2>
<hr>

  <%= form_for @employee do |f| %>
	<% if @employee.errors.any? %>
		<% @employee.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
    <% end %>
	
	<div>
	<p>
		<h5><b><%= f.label :name %><br></b></h5>
		<%= f.text_field :name %>	
	</p>
	
	<p>
		<h5><b><%= f.label :age %><br></b></h5>
		<%= f.text_field :age %>	
	</p>
	
	<p>
		<h5><b><%= f.label :designation %><br></b></h5>
		<%= f.text_field :designation %>	
	</p>
	
	<p>
		<h5><b> <%= f.label :gender %><br></b></h5>	
 		<%= f.radio_button(:gender, 'male') %>
 		<b><%= f.label("Male", :Male) %></b>
		<%= f.radio_button(:gender, 'female')%>
		<b><%= f.label("Female", :Female) %></b>	
	</p>
	</div>
<hr>
	<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>

<% end %>	

app/views/employees/show.html.erb
<h2 style="color:#11510f;">Employee details</h2>
<hr>
<h4><strong>Name : </strong><%= @employee.name %><br>
 	<b>Age : </b><%= @employee.age %><br>
	<b>Gender : </b><%= @employee.gender %><br>
	<b>Designation : </b><%= @employee.designation %><br>
	</h4>

	<hr>

	<%= link_to "Edit" ,edit_employee_path, :class => 'btn btn-primary' %>
	
	<%= link_to "Delete" ,@employee, method: :delete,data:{confirm: 'Are you sure you want to delete?'}, :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Employees</title>
    
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>


    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      
      <div class="collapse navbar-collapse" id="navbarCollapse" >
        <ul class="navbar-nav mr-auto">
          
          <li class="nav-item active ">
             <%= link_to "Home", home_path, {:class => 'nav-link'} %>
          </li>
          
          <li class="nav-item active">
            <%= link_to " Add Employee", new_employee_path, {:class => 'nav-link'} %>
          
          </li>

        </ul>
      </div>
      
    </nav>


	<div class="container" align="center">
    	<div class="jumbotron">
    		<%= yield %>
    	</div>
	</div>



  </body>
</html>